### ISSUE TITLE
Hello, can you share the background code? I'm learning webrtc 。Your code is great. I've learned a lot。

### ISSUE THREAD

**Issue by JessonYue** [rohg007/webrtc-android-p2p-room#1]
Hello, can you share the background code? I'm learning webrtc 。Your code is great. I've learned a lot。

**Comment by JessonYue** [comment]
你好，你的代码很棒 可以学习下你的后台代码吗？

**Comment by rohg007** [comment]
Thanks, @JessonYue, here's the signaling server that I used. https://github.com/rohg007/webrtcsignallingserver
